'use strict';

/**
 * Unit tests for src/ini-builder.js (buildIniFiles).
 *
 * Offline + deterministic: real temp dirs, no network, no compiler.
 * Compiled-plugin object shape (see src/compiler.js runCompile):
 *   { amxxName, plugins_ini_postfix, skipIni, repo, ref }
 */

const { test } = require('node:test');
const assert = require('node:assert/strict');

const fs   = require('fs');
const os   = require('os');
const path = require('path');

const { buildIniFiles } = require('../src/ini-builder');

function makeTmpDir(prefix) {
  return fs.mkdtempSync(path.join(os.tmpdir(), prefix));
}

function plugin(overrides) {
  return {
    amxxName: 'plugin.amxx',
    plugins_ini_postfix: undefined,
    skipIni: false,
    repo: 'Org/Repo',
    ref: 'v1.2.3',
    ...overrides,
  };
}

const CONFIGS_REL = path.join('amxmodx', 'configs');

test('buildIniFiles: empty array is a no-op (no configs dir created)', (t) => {
  const buildDir = makeTmpDir('amxb-ini-empty-');
  t.after(() => fs.rmSync(buildDir, { recursive: true, force: true }));

  buildIniFiles([], buildDir);

  assert.equal(fs.existsSync(path.join(buildDir, 'amxmodx')), false);
});

test('buildIniFiles: undefined postfix writes plugins.ini with header + single Source block', (t) => {
  const buildDir = makeTmpDir('amxb-ini-plain-');
  t.after(() => fs.rmSync(buildDir, { recursive: true, force: true }));

  buildIniFiles([
    plugin({ amxxName: 'first.amxx' }),
    plugin({ amxxName: 'second.amxx' }),
  ], buildDir);

  const iniPath = path.join(buildDir, CONFIGS_REL, 'plugins.ini');
  assert.equal(fs.existsSync(iniPath), true);
  assert.equal(fs.readFileSync(iniPath, 'utf8'), [
    '; Generated by amxx-builder',
    '',
    '; Source: Org/Repo @ v1.2.3',
    'first.amxx',
    'second.amxx',
    '',
  ].join('\n'));
});

test('buildIniFiles: empty-string postfix is falsy → plugins.ini', (t) => {
  const buildDir = makeTmpDir('amxb-ini-empty-postfix-');
  t.after(() => fs.rmSync(buildDir, { recursive: true, force: true }));

  buildIniFiles([plugin({ amxxName: 'only.amxx', plugins_ini_postfix: '' })], buildDir);

  const iniPath = path.join(buildDir, CONFIGS_REL, 'plugins.ini');
  assert.equal(fs.existsSync(iniPath), true);
  assert.equal(fs.existsSync(path.join(buildDir, CONFIGS_REL, 'plugins-.ini')), false);
  assert.match(fs.readFileSync(iniPath, 'utf8'), /only\.amxx/);
});

test('buildIniFiles: truthy postfix writes plugins-<postfix>.ini', (t) => {
  const buildDir = makeTmpDir('amxb-ini-postfix-');
  t.after(() => fs.rmSync(buildDir, { recursive: true, force: true }));

  buildIniFiles([plugin({ amxxName: 'vip_core.amxx', plugins_ini_postfix: 'vipm' })], buildDir);

  const iniPath = path.join(buildDir, CONFIGS_REL, 'plugins-vipm.ini');
  assert.equal(fs.existsSync(iniPath), true);
  assert.equal(fs.existsSync(path.join(buildDir, CONFIGS_REL, 'plugins.ini')), false);
  assert.equal(fs.readFileSync(iniPath, 'utf8'), [
    '; Generated by amxx-builder',
    '',
    '; Source: Org/Repo @ v1.2.3',
    'vip_core.amxx',
    '',
  ].join('\n'));
});

test('buildIniFiles: groups plugins by postfix into separate ini files', (t) => {
  const buildDir = makeTmpDir('amxb-ini-groups-');
  t.after(() => fs.rmSync(buildDir, { recursive: true, force: true }));

  buildIniFiles([
    plugin({ amxxName: 'base.amxx' }),
    plugin({ amxxName: 'vip_core.amxx', plugins_ini_postfix: 'vipm' }),
    plugin({ amxxName: 'vip_extras.amxx', plugins_ini_postfix: 'vipm' }),
    plugin({ amxxName: 'other.amxx' }),
  ], buildDir);

  assert.equal(fs.readFileSync(path.join(buildDir, CONFIGS_REL, 'plugins.ini'), 'utf8'), [
    '; Generated by amxx-builder',
    '',
    '; Source: Org/Repo @ v1.2.3',
    'base.amxx',
    'other.amxx',
    '',
  ].join('\n'));

  assert.equal(fs.readFileSync(path.join(buildDir, CONFIGS_REL, 'plugins-vipm.ini'), 'utf8'), [
    '; Generated by amxx-builder',
    '',
    '; Source: Org/Repo @ v1.2.3',
    'vip_core.amxx',
    'vip_extras.amxx',
    '',
  ].join('\n'));
});

test('buildIniFiles: skipIni plugins are excluded', (t) => {
  const buildDir = makeTmpDir('amxb-ini-skip-');
  t.after(() => fs.rmSync(buildDir, { recursive: true, force: true }));

  buildIniFiles([
    plugin({ amxxName: 'kept.amxx' }),
    plugin({ amxxName: 'hidden.amxx', skipIni: true }),
  ], buildDir);

  const content = fs.readFileSync(path.join(buildDir, CONFIGS_REL, 'plugins.ini'), 'utf8');
  assert.match(content, /kept\.amxx/);
  assert.doesNotMatch(content, /hidden\.amxx/);
});

test('buildIniFiles: all-skipIni plugins → no ini file written', (t) => {
  const buildDir = makeTmpDir('amxb-ini-all-skip-');
  t.after(() => fs.rmSync(buildDir, { recursive: true, force: true }));

  buildIniFiles([
    plugin({ amxxName: 'hidden1.amxx', skipIni: true }),
    plugin({ amxxName: 'hidden2.amxx', skipIni: true }),
  ], buildDir);

  assert.equal(fs.existsSync(path.join(buildDir, CONFIGS_REL)), true);
  assert.equal(fs.readdirSync(path.join(buildDir, CONFIGS_REL)).length, 0);
});

test('buildIniFiles: repo/ref change starts a new Source block (even returning to an earlier repo)', (t) => {
  const buildDir = makeTmpDir('amxb-ini-blocks-');
  t.after(() => fs.rmSync(buildDir, { recursive: true, force: true }));

  buildIniFiles([
    plugin({ amxxName: 'a.amxx', repo: 'Org/Alpha', ref: 'v1' }),
    plugin({ amxxName: 'b.amxx', repo: 'Org/Alpha', ref: 'v1' }),
    plugin({ amxxName: 'c.amxx', repo: 'Org/Beta', ref: 'v2' }),
    plugin({ amxxName: 'd.amxx', repo: 'Org/Alpha', ref: 'v1' }),
  ], buildDir);

  assert.equal(fs.readFileSync(path.join(buildDir, CONFIGS_REL, 'plugins.ini'), 'utf8'), [
    '; Generated by amxx-builder',
    '',
    '; Source: Org/Alpha @ v1',
    'a.amxx',
    'b.amxx',
    '',
    '; Source: Org/Beta @ v2',
    'c.amxx',
    '',
    '; Source: Org/Alpha @ v1',
    'd.amxx',
    '',
  ].join('\n'));
});

test('buildIniFiles: same repo with different refs gets separate Source blocks', (t) => {
  const buildDir = makeTmpDir('amxb-ini-refs-');
  t.after(() => fs.rmSync(buildDir, { recursive: true, force: true }));

  buildIniFiles([
    plugin({ amxxName: 'stable.amxx', repo: 'Org/Repo', ref: 'v1.0.0' }),
    plugin({ amxxName: 'dev.amxx', repo: 'Org/Repo', ref: 'master' }),
  ], buildDir);

  const content = fs.readFileSync(path.join(buildDir, CONFIGS_REL, 'plugins.ini'), 'utf8');
  assert.match(content, /; Source: Org\/Repo @ v1\.0\.0/);
  assert.match(content, /; Source: Org\/Repo @ master/);
});

test('buildIniFiles: local plugins render as "(local) @ local" source', (t) => {
  const buildDir = makeTmpDir('amxb-ini-local-');
  t.after(() => fs.rmSync(buildDir, { recursive: true, force: true }));

  buildIniFiles([
    plugin({ amxxName: 'local_one.amxx', repo: '(local)', ref: 'local' }),
    plugin({ amxxName: 'local_two.amxx', repo: '(local)', ref: 'local' }),
  ], buildDir);

  assert.equal(fs.readFileSync(path.join(buildDir, CONFIGS_REL, 'plugins.ini'), 'utf8'), [
    '; Generated by amxx-builder',
    '',
    '; Source: (local) @ local',
    'local_one.amxx',
    'local_two.amxx',
    '',
  ].join('\n'));
});
