@echo off
REM Quick-build script generated by `amxb init --script`
REM Builds the server package from amxbuild.yml in this directory.
amxb build
if errorlevel 1 (
  echo.
  echo Build failed. Fix the errors above and run this script again.
  pause
  exit /b 1
)
pause
